### ISSUE TITLE
Useless var

### ISSUE THREAD

**Issue by tilap** [koack/koack#12]
Useless production var

https://github.com/koack/koack/blob/2ee2114a57e69590a0b0313b0683ea4f98c8482e/pool.js#L1

**Comment by christophehurpeau** [comment]
utilisé ici: https://github.com/koack/koack/blob/2ee2114a57e69590a0b0313b0683ea4f98c8482e/pool.js#L7

**Comment by tilap** [comment]
Oh my mistake sorry :/
